### ISSUE TITLE
بدون عنوان

### ISSUE THREAD

**Issue by mskf1383** [PooyaRezaee/TextDad#1]
<div dir="rtl">

منم قبلا روی یه همچین پروژه ای کار می کردم
[https://github.com/mskf1383/ParsiNote_Lite](https://github.com/mskf1383/ParsiNote_Lite)
ولی متاسفانه به مشکل برخوردم
حتما یه نگاهی بهش بنداز
می تونه خیلی کمکت کنه :)
</div>

**Comment by PooyaRezaee** [comment]
سلام من پروژتونو دیدم قسمت استفاده از  سی اس اس و شورت کات ها ها جالب بود و خیلی کمکم کرد حتما پروژمو به زودی اپدیت میکنم و داخلش از سی اس اس و شورت کات ها استفاده کنم
